# a simple Makefile

SENDER = termux-share -a send
VIEWER = viewpdf

SECTIONS := $(wildcard section_*/section.tex)

TIKZPICS := $(wildcard */**/tikzpics/*.tex)

build: chapter.pdf view

force:
	lunatikz build chapter.tex
	pdflatex -shell-escape -halt-on-error chapter.tex
	$(VIEWER) chapter.pdf

chapter.pdf: chapter.tex ../preamble.tex ../colorscheme.sty ../course.tex syllabus.tex $(SECTIONS) $(TIKZPICS)
	lunatikz build chapter.tex
	pdflatex -shell-escape -halt-on-error chapter.tex

view:
	$(VIEWER) chapter.pdf

send:
	$(SENDER) chapter.pdf

.PHONY: view build force
